export const INITIAL_MEMBERS = [
  {
    name: "BALOLONG, GLORIA",
    last_name: "BALOLONG",
    first_name: "GLORIA",
    plate_no: "CVH909",
    route: "TONDALIGAN",
    capital_share: 0,
    refund: 0,
    capital_build_up: 0,
    total_capital_share: 0,
    gender: "F",
    role: "member"
  },
  {
    name: "BALOLONG, MIGUEL",
    last_name: "BALOLONG",
    first_name: "MIGUEL",
    registered_name: "RAMIREZ, BERNIE",
    plate_no: "PEM587",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    total_capital_share: 10000,
    dividend: 5007.52,
    gender: "M",
    role: "member"
  },
  {
    name: "BALOLONG, MIGUEL",
    last_name: "BALOLONG",
    first_name: "MIGUEL",
    registered_name: "DE VERA, LAURETO",
    plate_no: "AVM363",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 3200,
    total_capital_share: 13200,
    dividend: 6609.93,
    role: "member"
  },
  {
    name: "BATOL, SANNY",
    last_name: "BATOL",
    first_name: "SANNY",
    plate_no: "AVJ287",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 800,
    total_capital_share: 10800,
    dividend: 5408.12,
    gender: "M",
    role: "member"
  },
  {
    name: "PARAGAS, EVELYN",
    last_name: "PARAGAS",
    first_name: "EVELYN",
    registered_name: "CABRERA LYWEN",
    plate_no: "DJG135",
    route: "TONDALIGAN",
    capital_share: 20000,
    capital_build_up: 1600,
    total_capital_share: 21600,
    dividend: 10816.25,
    gender: "F",
    role: "member"
  },
  {
    name: "CASTRES, ALBERTO",
    last_name: "CASTRES",
    first_name: "ALBERTO",
    plate_no: "AAU993/AVR135",
    route: "BINLOC",
    capital_share: 20000,
    capital_build_up: 2400,
    total_capital_share: 22400,
    dividend: 11216.85,
    gender: "M",
    role: "member"
  },
  {
    name: "CASTRES, JESUS",
    last_name: "CASTRES",
    first_name: "JESUS",
    plate_no: "AVZ947",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 20000,
    capital_build_up: 400,
    total_capital_share: 400,
    dividend: 10015.05,
    gender: "M",
    role: "member"
  },
  {
    name: "CASTRES, JESUS",
    last_name: "CASTRES",
    first_name: "JESUS",
    plate_no: "AVX983",
    route: "TONDALIGAN",
    capital_share: 20000,
    total_capital_share: 20000,
    role: "member"
  },
  {
    name: "CASTRES, MARIA ANNA",
    last_name: "CASTRES",
    first_name: "MARIA ANNA",
    plate_no: "AVR457/AVT350",
    route: "BINLOC",
    capital_share: 20000,
    capital_build_up: 2400,
    total_capital_share: 22400,
    dividend: 11216.85,
    gender: "F",
    role: "member"
  },
  {
    name: "CASTRES, MARIA ANNA",
    last_name: "CASTRES",
    first_name: "MARIA ANNA",
    plate_no: "PFJ 281",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    total_capital_share: 10000,
    dividend: 5007.52,
    role: "member"
  },
  {
    name: "CASTRES, RYAN AND VENESSA",
    last_name: "CASTRES",
    first_name: "RYAN AND VENESSA",
    plate_no: "AVL780",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2400,
    total_capital_share: 12400,
    dividend: 6209.33,
    gender: "M",
    role: "member"
  },
  {
    name: "CASTRES, ZENAIDA",
    last_name: "CASTRES",
    first_name: "ZENAIDA",
    plate_no: "AVJ221/AVM368",
    route: "BINLOC/TONDALIGAN",
    capital_share: 20000,
    capital_build_up: 2400,
    total_capital_share: 22400,
    dividend: 11216.85,
    gender: "F",
    role: "member"
  },
  {
    name: "CAYABYAB, ALEX",
    last_name: "CAYABYAB",
    first_name: "ALEX",
    plate_no: "AVS349",
    route: "TONDALIGAN",
    capital_share: 13000,
    refund: 3000,
    capital_build_up: 400,
    total_capital_share: 10400,
    dividend: 5207.82,
    gender: "M",
    role: "member"
  },
  {
    name: "RAMOS, REGIN",
    last_name: "RAMOS",
    first_name: "REGIN",
    registered_name: "CAYABYAB MARENE",
    plate_no: "AVR629",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 800,
    total_capital_share: 10800,
    dividend: 5408.12,
    gender: "M",
    role: "member"
  },
  {
    name: "CAYABYAB, SAMMY",
    last_name: "CAYABYAB",
    first_name: "SAMMY",
    plate_no: "AVH738",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 800,
    total_capital_share: 10800,
    dividend: 5408.12,
    gender: "M",
    role: "member"
  },
  {
    name: "CAYABYAB, SAMMY",
    last_name: "CAYABYAB",
    first_name: "SAMMY",
    plate_no: "AVX646",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    total_capital_share: 10000,
    dividend: 5007.12,
    role: "member"
  },
  {
    name: "CERVERA, TAYGORO",
    last_name: "CERVERA",
    first_name: "TAYGORO",
    registered_name: "CAYABYAB FILICIDAD",
    plate_no: "CFH875",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 1200,
    total_capital_share: 11200,
    dividend: 5207.82,
    gender: "M",
    role: "member"
  },
  {
    name: "CERVERA, GILBERT",
    last_name: "CERVERA",
    first_name: "GILBERT",
    plate_no: "AVH603",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 400,
    total_capital_share: 10400,
    dividend: 5207.82,
    gender: "M",
    role: "member"
  },
  {
    name: "CLAUNA, GLORIA",
    last_name: "CLAUNA",
    first_name: "GLORIA",
    registered_name: "BIAY, ROQUE",
    plate_no: "CEG572",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2400,
    total_capital_share: 12400,
    dividend: 6209.33,
    gender: "F",
    role: "member"
  },
  {
    name: "CLAUNA, GLORIA",
    last_name: "CLAUNA",
    first_name: "GLORIA",
    registered_name: "NATULAN, MAXIMO",
    plate_no: "AVZ943",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    total_capital_share: 10000,
    dividend: 5007.52,
    role: "member"
  },
  {
    name: "DE GUZMAN, ARMANDO",
    last_name: "DE GUZMAN",
    first_name: "ARMANDO",
    plate_no: "AVT398",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    total_capital_share: 10000,
    dividend: 5007.52,
    gender: "M",
    role: "member"
  },
  {
    name: "DE VERA, FAUSTINO",
    last_name: "DE VERA",
    first_name: "FAUSTINO",
    plate_no: "NNK915",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    total_capital_share: 10000,
    dividend: 5007.52,
    gender: "M",
    role: "member"
  },
  {
    name: "DE VERA, FRANCISCO",
    last_name: "DE VERA",
    first_name: "FRANCISCO",
    plate_no: "AVH908",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2400,
    total_capital_share: 12400,
    dividend: 6209.33,
    gender: "M",
    role: "member"
  },
  {
    name: "DELA CRUZ, FELICIDAD",
    last_name: "DELA CRUZ",
    first_name: "FELICIDAD",
    plate_no: "AAP761",
    route: "TONDALIGAN",
    capital_share: 0,
    total_capital_share: 0,
    gender: "F",
    role: "member"
  },
  {
    name: "DELA CRUZ, GENMIN",
    last_name: "DELA CRUZ",
    first_name: "GENMIN",
    plate_no: "AVP615",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2400,
    total_capital_share: 12400,
    dividend: 6209.33,
    gender: "M",
    role: "member"
  },
  {
    name: "DIZO, RENATO",
    last_name: "DIZO",
    first_name: "RENATO",
    plate_no: "AVT579",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2400,
    total_capital_share: 12400,
    dividend: 6209.33,
    gender: "M",
    role: "member"
  },
  {
    name: "DOCTOLERO, RASAVER",
    last_name: "DOCTOLERO",
    first_name: "RASAVER",
    registered_name: "ABRIO, MARIFI AND BERNI",
    plate_no: "AVL975",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2400,
    total_capital_share: 12400,
    dividend: 6209.33,
    gender: "M",
    role: "member"
  },
  {
    name: "DUMLAO, LUISITO & ELVIE",
    last_name: "DUMLAO",
    first_name: "LUISITO & ELVIE",
    plate_no: "PCB623",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    total_capital_share: 10000,
    dividend: 5007.52,
    gender: "M",
    role: "member"
  },
  {
    name: "DUMLAO, LUISITO & ELVIE",
    last_name: "DUMLAO",
    first_name: "LUISITO & ELVIE",
    plate_no: "AVT266",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    total_capital_share: 10000,
    dividend: 5007.52,
    role: "member"
  },
  {
    name: "FERNANDEZ, MARISSA",
    last_name: "FERNANDEZ",
    first_name: "MARISSA",
    plate_no: "AWA679",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2400,
    total_capital_share: 12400,
    dividend: 6209.33,
    gender: "F",
    role: "member"
  },
  {
    name: "FERRER, JESUSA",
    last_name: "FERRER",
    first_name: "JESUSA",
    registered_name: "CABRAS JEFFREY",
    plate_no: "AAZ542",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 1200,
    total_capital_share: 11200,
    dividend: 5608.43,
    gender: "F",
    role: "member"
  },
  {
    name: "RAMOS, FRELAN",
    last_name: "RAMOS",
    first_name: "FRELAN",
    registered_name: "GABRILLO EFREN",
    plate_no: "AVJ120",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 400,
    total_capital_share: 10400,
    dividend: 5207.82,
    gender: "M",
    role: "member"
  },
  {
    name: "GONZALES, GILBERT",
    last_name: "GONZALES",
    first_name: "GILBERT",
    plate_no: "AVX876",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 400,
    total_capital_share: 10400,
    dividend: 5207.82,
    gender: "M",
    role: "member"
  },
  {
    name: "IMASA, VICENTE",
    last_name: "IMASA",
    first_name: "VICENTE",
    plate_no: "AWA531",
    route: "TONDALIGAN",
    capital_share: 0,
    total_capital_share: 0,
    gender: "M",
    role: "member"
  },
  {
    name: "IMASA, VICENTE",
    last_name: "IMASA",
    first_name: "VICENTE",
    plate_no: "AVU456",
    route: "TONDALIGAN",
    capital_share: 0,
    total_capital_share: 0,
    role: "member"
  },
  {
    name: "JACOBE, JESUS",
    last_name: "JACOBE",
    first_name: "JESUS",
    plate_no: "AVR622",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2000,
    total_capital_share: 12000,
    dividend: 6009.03,
    gender: "M",
    role: "member"
  },
  {
    name: "JUGO, MARIA MILAGROS",
    last_name: "JUGO",
    first_name: "MARIA MILAGROS",
    plate_no: "AVW658",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 400,
    total_capital_share: 10400,
    dividend: 5207.82,
    gender: "F",
    role: "member"
  },
  {
    name: "LANDINGIN, ALAIN",
    last_name: "LANDINGIN",
    first_name: "ALAIN",
    plate_no: "012003",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 1200,
    total_capital_share: 11200,
    dividend: 5608.43,
    gender: "M",
    role: "member"
  },
  {
    name: "LLANERA, GLENN",
    last_name: "LLANERA",
    first_name: "GLENN",
    plate_no: "CVD193",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 1600,
    total_capital_share: 11600,
    dividend: 5808.73,
    gender: "M",
    role: "member"
  },
  {
    name: "OLLET, RAMIRO JR",
    last_name: "OLLET",
    first_name: "RAMIRO JR",
    registered_name: "MAYO JOEL",
    plate_no: "AVS780",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 1600,
    total_capital_share: 11600,
    dividend: 5808.73,
    gender: "M",
    role: "member"
  },
  {
    name: "MEJIA, MARIELYN",
    last_name: "MEJIA",
    first_name: "MARIELYN",
    plate_no: "AVN807",
    route: "TONDALIGAN",
    capital_share: 20000,
    capital_build_up: 800,
    total_capital_share: 20800,
    dividend: 10415.65,
    gender: "F",
    role: "member"
  },
  {
    name: "MEJIA, RENATO",
    last_name: "MEJIA",
    first_name: "RENATO",
    plate_no: "AWC432",
    route: "TONDALIGAN",
    capital_share: 20000,
    total_capital_share: 20000,
    dividend: 10015.05,
    gender: "M",
    role: "member"
  },
  {
    name: "MENESES, VIRGILIO",
    last_name: "MENESES",
    first_name: "VIRGILIO",
    plate_no: "AVZ689",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2400,
    total_capital_share: 12400,
    dividend: 6209.33,
    gender: "M",
    role: "member"
  },
  {
    name: "NARAG, JAIME",
    last_name: "NARAG",
    first_name: "JAIME",
    plate_no: "NVS736",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2400,
    total_capital_share: 12400,
    dividend: 6209.33,
    gender: "M",
    role: "member"
  },
  {
    name: "NARVASA, ROMEO",
    last_name: "NARVASA",
    first_name: "ROMEO",
    plate_no: "ABX253",
    route: "TONDALIGAN",
    capital_share: 27000,
    refund: 10000,
    capital_build_up: 800,
    total_capital_share: 17800,
    dividend: 8913.39,
    gender: "M",
    role: "member"
  },
  {
    name: "OCAMPO, PATRICIO",
    last_name: "OCAMPO",
    first_name: "PATRICIO",
    registered_name: "JEFRY MORRES",
    plate_no: "TJU317",
    route: "TONDALIGAN",
    capital_share: 20000,
    total_capital_share: 20000,
    dividend: 10007.52,
    gender: "M",
    role: "member"
  },
  {
    name: "ODA, MODESTO",
    last_name: "ODA",
    first_name: "MODESTO",
    registered_name: "IMBORNAL WILLY",
    plate_no: "DJA291",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2400,
    total_capital_share: 12400,
    dividend: 6209.33,
    gender: "M",
    role: "member"
  },
  {
    name: "ORNAFIO, ANACETO",
    last_name: "ORNAFIO",
    first_name: "ANACETO",
    registered_name: "CASTRES, ZENAIDA",
    plate_no: "AVU738",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2400,
    total_capital_share: 12400,
    dividend: 6209.33,
    gender: "M",
    role: "member"
  },
  {
    name: "ORTE, JESUS",
    last_name: "ORTE",
    first_name: "JESUS",
    plate_no: "AVT890",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2400,
    total_capital_share: 12400,
    dividend: 6209.33,
    gender: "M",
    role: "member"
  },
  {
    name: "PANEDA, ROMULO",
    last_name: "PANEDA",
    first_name: "ROMULO",
    plate_no: "NXJ348",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2400,
    total_capital_share: 12400,
    dividend: 6209.33,
    gender: "M",
    role: "member"
  },
  {
    name: "PANEDA, SATURNINA",
    last_name: "PANEDA",
    first_name: "SATURNINA",
    plate_no: "AVV148",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2400,
    total_capital_share: 12400,
    dividend: 6209.33,
    gender: "F",
    role: "member"
  },
  {
    name: "PARAS, ESSONY",
    last_name: "PARAS",
    first_name: "ESSONY",
    plate_no: "AVN785",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    total_capital_share: 10000,
    dividend: 5007.52,
    gender: "M",
    role: "member"
  },
  {
    name: "RABGO, BOBBY",
    last_name: "RABGO",
    first_name: "BOBBY",
    plate_no: "AVV473",
    route: "BINLOC",
    capital_share: 20000,
    capital_build_up: 2400,
    total_capital_share: 22400,
    dividend: 11216.85,
    gender: "M",
    role: "member"
  },
  {
    name: "RAMILLANO, GRACE",
    last_name: "RAMILLANO",
    first_name: "GRACE",
    plate_no: "ACL271",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 1200,
    total_capital_share: 11200,
    dividend: 5608.43,
    gender: "F",
    role: "member"
  },
  {
    name: "RAMOS, HERCULANO JR.",
    last_name: "RAMOS",
    first_name: "HERCULANO JR.",
    plate_no: "AVR602",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 1600,
    total_capital_share: 11600,
    dividend: 5808.73,
    gender: "M",
    role: "member"
  },
  {
    name: "RELOSIMON, MARNIE",
    last_name: "RELOSIMON",
    first_name: "MARNIE",
    plate_no: "AVG992",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 400,
    total_capital_share: 10400,
    dividend: 5207.82,
    gender: "M",
    role: "member"
  },
  {
    name: "SEMBRANA, MA. DELIA",
    last_name: "SEMBRANA",
    first_name: "MA. DELIA",
    plate_no: "AVZ189",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 1200,
    total_capital_share: 11200,
    dividend: 5608.43,
    gender: "F",
    role: "member"
  },
  {
    name: "SOLIS, BOBBY",
    last_name: "SOLIS",
    first_name: "BOBBY",
    registered_name: "SOLIS, BERNARDO JR.",
    plate_no: "AVZ327",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2400,
    total_capital_share: 12400,
    dividend: 6209.33,
    gender: "M",
    role: "member"
  },
  {
    name: "SONGCUAN, MARIBETH",
    last_name: "SONGCUAN",
    first_name: "MARIBETH",
    plate_no: "AVU721",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2400,
    total_capital_share: 12400,
    dividend: 6209.33,
    gender: "F",
    role: "member"
  },
  {
    name: "SOY, JOHN DEXTER",
    last_name: "SOY",
    first_name: "JOHN DEXTER",
    plate_no: "AVT278",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 800,
    total_capital_share: 10800,
    dividend: 5408.12,
    gender: "M",
    role: "member"
  },
  {
    name: "TORALBA, SILVERIO",
    last_name: "TORALBA",
    first_name: "SILVERIO",
    plate_no: "AVX875",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 800,
    total_capital_share: 10800,
    dividend: 5408.12,
    gender: "M",
    role: "member"
  },
  {
    name: "TULIAO, ROGELIO",
    last_name: "TULIAO",
    first_name: "ROGELIO",
    plate_no: "AAN689",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2000,
    total_capital_share: 12000,
    dividend: 6009.03,
    gender: "M",
    role: "member"
  },
  {
    name: "UBANDO, MERELINA",
    last_name: "UBANDO",
    first_name: "MERELINA",
    registered_name: "AGUILAR, ROMANO & ROWENA",
    plate_no: "AVU409",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    total_capital_share: 10000,
    dividend: 5007.52,
    gender: "F",
    role: "member"
  },
  {
    name: "UBANDO, MERELINA",
    last_name: "UBANDO",
    first_name: "MERELINA",
    registered_name: "DULAY, MELANIE AND FRANCIS",
    plate_no: "AVT844",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 2400,
    total_capital_share: 12400,
    dividend: 6209.33,
    role: "member"
  },
  {
    name: "UBANDO, ALBERTO",
    last_name: "UBANDO",
    first_name: "ALBERTO",
    plate_no: "AVL126",
    route: "TONDALIGAN",
    capital_share: 20000,
    capital_build_up: 2000,
    total_capital_share: 22000,
    dividend: 11009.03,
    gender: "M",
    role: "member"
  },
  {
    name: "UBANDO, DOMICIANO",
    last_name: "UBANDO",
    first_name: "DOMICIANO",
    plate_no: "AVX670",
    route: "TONDALIGAN",
    capital_share: 20000,
    refund: 10000,
    total_capital_share: 10000,
    dividend: 5007.52,
    gender: "M",
    role: "member"
  },
  {
    name: "UBANDO, ELISA",
    last_name: "UBANDO",
    first_name: "ELISA",
    plate_no: "AVR641",
    route: "TONDALIGAN",
    capital_share: 20000,
    total_capital_share: 20000,
    dividend: 10015.05,
    gender: "F",
    role: "member"
  },
  {
    name: "ASURIN, FERNANDO",
    last_name: "ASURIN",
    first_name: "FERNANDO",
    plate_no: "AVX 301",
    route: "BINLOC",
    capital_share: 0,
    total_capital_share: 0,
    role: "member"
  },
  {
    name: "BALIOLA, JIMMY/EDITHA",
    last_name: "BALIOLA",
    first_name: "JIMMY/EDITHA",
    plate_no: "AVG915",
    route: "BINLOC",
    capital_share: 20000,
    capital_build_up: 800,
    total_capital_share: 20800,
    dividend: 10415.65,
    role: "member"
  },
  {
    name: "CASTRES, WENIE",
    last_name: "CASTRES",
    first_name: "WENIE",
    registered_name: "FERNANDO ROSARIO",
    plate_no: "AVZ166",
    route: "BINLOC",
    capital_share: 20000,
    refund: 10000,
    capital_build_up: 400,
    total_capital_share: 10400,
    dividend: 5207.82,
    role: "member"
  },
  {
    name: "CASTRES, ALBERTO",
    last_name: "CASTRES",
    first_name: "ALBERTO",
    plate_no: "AVR135",
    route: "BINLOC",
    total_capital_share: 0,
    role: "member"
  },
  {
    name: "CASTRES, MARIA ANNA",
    last_name: "CASTRES",
    first_name: "MARIA ANNA",
    plate_no: "AVN 886",
    route: "TONDALIGAN",
    total_capital_share: 0,
    role: "member"
  },
  {
    name: "CASTRES, ZENAIDA",
    last_name: "CASTRES",
    first_name: "ZENAIDA",
    plate_no: "AVM368",
    route: "TONDALIGAN",
    total_capital_share: 0,
    role: "member"
  },
  {
    name: "CAYABYAB, LETECIA",
    last_name: "CAYABYAB",
    first_name: "LETECIA",
    plate_no: "AVU372/CLG868",
    route: "BINLOC",
    capital_share: 20000,
    capital_build_up: 800,
    total_capital_share: 20800,
    dividend: 10415.65,
    role: "member"
  },
  {
    name: "FERAREN, SERAFEN JR",
    last_name: "FERAREN",
    first_name: "SERAFEN JR",
    plate_no: "AVX182",
    route: "TONDALIGAN",
    capital_share: 20000,
    capital_build_up: 2000,
    total_capital_share: 22000,
    dividend: 11016.55,
    role: "member"
  },
  {
    name: "GONZALES, REGGIE",
    last_name: "GONZALES",
    first_name: "REGGIE",
    plate_no: "CFU760",
    route: "TONDALIGAN",
    capital_share: 10000,
    capital_build_up: 400,
    total_capital_share: 10400,
    dividend: 5207.82,
    role: "member"
  },
  {
    name: "RAMOS, HERCULANO JR.",
    last_name: "RAMOS",
    first_name: "HERCULANO JR.",
    plate_no: "PGB835",
    route: "TONDALIGAN",
    capital_share: 10000,
    total_capital_share: 10000,
    dividend: 5007.52,
    role: "member"
  },
  {
    name: "SEMBRANA, MARGIE",
    last_name: "SEMBRANA",
    first_name: "MARGIE",
    plate_no: "CVR584",
    route: "TONDALIGAN",
    capital_share: 20000,
    total_capital_share: 20000,
    dividend: 10015.05,
    role: "member"
  },
  {
    name: "CALAUNAN, ARIES",
    last_name: "CALAUNAN",
    first_name: "ARIES",
    plate_no: "CVH909",
    route: "TONDALIGAN",
    capital_share: 10000,
    total_capital_share: 10000,
    dividend: 5007.52,
    role: "member"
  },
  {
    name: "DE GUZMAN, HAROLD",
    last_name: "DE GUZMAN",
    first_name: "HAROLD",
    plate_no: "AVT266",
    route: "TONDALIGAN",
    capital_share: 5000,
    total_capital_share: 5000,
    dividend: 2503.76,
    role: "member"
  },
  {
    name: "BILLOCILIO, ROGEMIL",
    last_name: "BILLOCILIO",
    first_name: "ROGEMIL",
    plate_no: "AVJ287",
    route: "TONDALIGAN",
    capital_share: 5000,
    total_capital_share: 5000,
    dividend: 2503.76,
    role: "member"
  },
  {
    name: "FERRER, DANILO",
    last_name: "FERRER",
    first_name: "DANILO",
    route: "TONDALIGAN",
    capital_share: 10000,
    total_capital_share: 10000,
    role: "member"
  },
  {
    name: "MARARAC, ARMANDO",
    last_name: "MARARAC",
    first_name: "ARMANDO",
    plate_no: "AWA531/AVU456",
    route: "TONDALIGAN",
    capital_share: 10000,
    total_capital_share: 10000,
    role: "member"
  },
  {
    name: "BATOL, SANNY",
    last_name: "BATOL",
    first_name: "SANNY",
    capital_build_up: 10000,
    total_capital_share: 10000,
    role: "member"
  }
];
